name = "status-fae-dev"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_GITHUB_RELEASES", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
